services:
  - type: web
    name: daily-meditation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.api.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DEBUG_MODE
        value: false
      - key: TTS_VOICE_MODEL
        value: en_US-lessac-medium
    healthCheckPath: /
    autoDeploy: true 